version: 0.0
os: linux
files:
  – source: /
    destination: /home/rails/graphickers-hub
permissions:
  – object: /home/rails/graphickers-hub
    pattern: "**"
    owner: rails
    group: rails
    mode: 775
    type:
      – file