version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails
permissions:
  - object: /var/www/rails
    pattern: "**"
    owner: root
    group: root
    mode: 775
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  BeforeInstall:
    - location: scripts/clean.sh
      runas: root
  AfterInstall:
    - location: scripts/prepare.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root